node ('SpotChrome'){

def branchName;
withEnv(["CHROME_BIN=/usr/bin/google-chrome-stable", "DISPLAY=:99.0", 'CI=true', "NODE_ENV=CI"]) {
        sh 'printenv'
    branchName = getCurrentBranch()
    echo 'My branch is: ' + branchName
}


  stage('Checkout') {
    checkout([$class: 'GitSCM', branches: [[name: branchName]],
      extensions       : [[$class: 'CloneOption', timeout: 30]],
      userRemoteConfigs: [[url: 'https://github.com/michal-shitrit/tic-tac-toe1.git']]
    ])
  }

  try {
    stage('Test') {
      withEnv(["CHROME_BIN=/usr/bin/google-chrome-stable", "DISPLAY=:99.0", 'CI=true', "NODE_ENV=CI"]) {
        sh 'printenv'
        timeout(40) {
              mvn363 'mvn -f tic-tac-toe/pom.xml clean install -s settings.xml'
          }
        }
      }
    } catch (Exception e) {
      println e
      currentBuild.result = 'UNSTABLE'
  }
}

def getCurrentBranch (){
    /*echo "branch::: $env.BRANCH_NAME"
    if ("$env.BRANCH_NAME" == 'main'){
      return  'main';
    }

    return "$env.CHANGE_BRANCH"*/
    return 'main'
}
